splash = false

preload = /home/cbels/Wallpaper/wallpaperflare.com_wallpaper.jpg
wallpaper = HDMI-A-1,/home/cbels/Wallpaper/wallpaperflare.com_wallpaper.jpg
wallpaper = DP-2,/home/cbels/Wallpaper/wallpaperflare.com_wallpaper.jpg
