context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "DT 1990 Pro EQ"
      media.name = "DT 1990 Pro EQ"
      filter.graph = {
        nodes = [
          { type = builtin
            name = eq
            label = param_eq
            config = { filename = "/home/cbels/.config/pipewire/eq/dt1990-analytical.txt" }
          }
        ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name = "eq_sink.dt1990"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name = "eq_output.dt1990"
        node.passive = true
        target.object = "alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_K7-00.analog-stereo"
      }
    }
  }
]
