context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "Sony MDR-1R"
      media.name = "Sony MDR-1R"
      filter.graph = {
        nodes = [
          { type = builtin
            name = eq
            label = param_eq
            config = { filename = "/home/cbels/.config/pipewire/eq/Sonymdr1r.txt" }
          }
        ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name = "eq_sink.mdr1r"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name = "eq_output.mdr1r"
        node.passive = true
        target.object = "alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_K7-00.analog-stereo"
      }
    }
  }
]
