# vim:ft=kitty

## name:     Gruvbox Dark
## upstream: https://github.com/morhetz/gruvbox

background            #282828
foreground            #ebdbb2
selection_background  #3c3836
selection_foreground  #ebdbb2

cursor            #ebdbb2
cursor_text_color #282828

url_color  #83a598

active_border_color   #83a598
inactive_border_color #3c3836
bell_border_color     #fabd2f

wayland_titlebar_color system
macos_titlebar_color   system

active_tab_foreground   #282828
active_tab_background   #83a598
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
tab_bar_background      #1d2021

mark1_foreground #282828
mark1_background #b8bb26
mark2_foreground #282828
mark2_background #fabd2f
mark3_foreground #282828
mark3_background #83a598

# 16 terminal colors

# black
color0  #282828
color8  #928374

# red
color1  #cc241d
color9  #fb4934

# green
color2  #98971a
color10 #b8bb26

# yellow
color3  #d79921
color11 #fabd2f

# blue
color4  #458588
color12 #83a598

# magenta
color5  #b16286
color13 #d3869b

# cyan
color6  #689d6a
color14 #8ec07c

# white
color7  #a89984
color15 #ebdbb2
